### ISSUE TITLE
Urllib3 version 2+ causes compatibility errors

### ISSUE THREAD

**Issue by katsikora** [maxplanck-ie/BigRedButton#50]
```
/home/pipegrp/.local/lib/python3.10/site-packages/requests/__init__.py:102: RequestsDependencyWarning: urllib3 (2.0.3) or chardet (None)/charset_normalizer (3.1.0) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({})/charset_normalizer ({}) doesn't match a supported "
Traceback (most recent call last):
  File "/home/pipegrp/.local/lib/python3.10/site-packages/requests_toolbelt/_compat.py", line 48, in <module>
    from requests.packages.urllib3.contrib import appengine as gaecontrib
ImportError: cannot import name 'appengine' from 'requests.packages.urllib3.contrib' (/localenv/pipegrp/anaconda/miniconda3/envs/BRB_dev_KS/lib/python3.10/site-packages/urllib3/contrib/__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/localenv/pipegrp/anaconda/miniconda3/envs/BRB_dev_KS/bin/BigRedButton.py", line 10, in <module>
    import BRB.PushButton
  File "/localenv/pipegrp/anaconda/miniconda3/envs/BRB_dev_KS/lib/python3.10/site-packages/BRB/PushButton.py", line 5, in <module>
    import BRB.galaxy
  File "/localenv/pipegrp/anaconda/miniconda3/envs/BRB_dev_KS/lib/python3.10/site-packages/BRB/galaxy.py", line 2, in <module>
    from bioblend.galaxy import GalaxyInstance
  File "/home/pipegrp/.local/lib/python3.10/site-packages/bioblend/galaxy/__init__.py", line 29, in <module>
    from bioblend.galaxyclient import GalaxyClient
  File "/home/pipegrp/.local/lib/python3.10/site-packages/bioblend/galaxyclient.py", line 17, in <module>
    from requests_toolbelt import MultipartEncoder
  File "/home/pipegrp/.local/lib/python3.10/site-packages/requests_toolbelt/__init__.py", line 12, in <module>
    from .adapters import SSLAdapter, SourceAddressAdapter
  File "/home/pipegrp/.local/lib/python3.10/site-packages/requests_toolbelt/adapters/__init__.py", line 12, in <module>
    from .ssl import SSLAdapter
  File "/home/pipegrp/.local/lib/python3.10/site-packages/requests_toolbelt/adapters/ssl.py", line 16, in <module>
    from .._compat import poolmanager
  File "/home/pipegrp/.local/lib/python3.10/site-packages/requests_toolbelt/_compat.py", line 50, in <module>
    from urllib3.contrib import appengine as gaecontrib
ImportError: cannot import name 'appengine' from 'urllib3.contrib' (/localenv/pipegrp/anaconda/miniconda3/envs/BRB_dev_KS/lib/python3.10/site-packages/urllib3/contrib/__init__.py)

```

**Comment by WardDeb** [comment]
This might've been some library mismatches as I see ~/.local paths are mixed with /localenv paths. Feel free to re-open if this is still an issue.
